#!/usr/bin/env sh

# tmux setup session

if [ -z "$1" ]; then
    echo "Missing directory. Usage: $0 <directory>"
    exit 1
fi

SESSION_DIR=$(realpath "$1")
if [ ! -d "$SESSION_DIR" ]; then
    echo "Invalid directory. Not found: $SESSION_DIR"
    exit 1
fi

SESSION_NAME=$(basename "$1")

# Session
tmux new-session -d -s $SESSION_NAME -A

# Main window 1 :: Setup
if [ -f "$SESSION_DIR/.nvimsession" ]; then
    tmux send-keys -t $SESSION_NAME "cd $SESSION_DIR;nvim -S .nvimsession;clear" C-m
else
    tmux send-keys -t $SESSION_NAME "cd $SESSION_DIR;nvim;clear" C-m
fi

tmux split-pane -t $SESSION_NAME
tmux send-keys -t $SESSION_NAME "cd $SESSION_DIR;clear" C-m
# Main window 1 :: Maximize editor
tmux select-pane -t $SESSION_NAME.+1
tmux resize-pane -Z -t $SESSION_NAME

# Sub window 2 :: Setup
#tmux new-window -t $SESSION_NAME
#tmux send-keys -t $SESSION_NAME "cd $SESSION_DIR;clear" C-m
#
#tmux split-pane -t $SESSION_NAME
#tmux send-keys -t $SESSION_NAME "cd $SESSION_DIR;clear" C-m

if [ -f "$SESSION_DIR/.tmux-ss" ]; then
    source "$SESSION_DIR/.tmux-ss"
fi

# reselect our editor
tmux select-window -t $SESSION_NAME:1
