#!/usr/bin/env bash

# Creates a wrapped shell environment
# TODO:
#   use overlayfs
#   check_env HOME
#   check_env PWD

SCRIPT_NAME=$(basename "$0")

print() {
    printf "\n[$SCRIPT_NAME] ${1}"
}

err_exit() {
    print "[error] ${1}"
    exit 1
}

check_command() {
    command -v "${1}" > /dev/null 2>&1
}

# ---

printf "[$SCRIPT_NAME] start..."

check_command bwrap || err_exit "'bwrap' is not installed or available"
check_command realpath || err_exit "'realpath' is not installed or available"

if [[ "${PWD}" == "${HOME}" || "${PWD}" != "${HOME}"/* ]]; then
    err_exit "invalid working directory! this is intentional as you might've tried to create a sandboxed shell environment in a path that defeats the purpose of the sandbox. directory: '${PWD}'"
fi

USE_TERM="${SHELL}"
ID="$(echo "${PWD}" | md5sum | awk '{ print $1 }')"
SBX_HOME_DIR="${HOME}/.${SCRIPT_NAME}/${ID}/home"
SBX_ENV_PATH="/usr/local/sbin:/usr/local/bin:/usr/bin"

print "sandbox id: '${ID}'"

if [ ! -d "${SBX_HOME_DIR}" ]; then
    print "creating sandboxed home..."
    mkdir -p ${SBX_HOME_DIR} || err_exit "failed to create home directory"
fi

print "setting up params... "
#--ro-bind /etc/resolv.conf /etc/resolv.conf            \
#    --ro-bind /etc/ssl /etc/ssl                            \
#    --ro-bind /etc/ca-certificates /etc/ca-certificates    \
#    --ro-bind /etc/subuid /etc/subuid    \
#    --ro-bind /etc/subgid /etc/subgid    \
#    --ro-bind /etc/passwd /etc/passwd    \
#    --ro-bind /etc/ca-certificates /etc/ca-certificates    \
#    --ro-bind /sys/fs/cgroup /sys/fs/cgroup                \

#    --chmod 755 /usr/bin/newuidmap \
#    --chmod 755 /usr/bin/newgidmap \

params+=(                                                  \
    --die-with-parent                                      \
    --unshare-all                                          \
    --clearenv                                             \
    --share-net                                            \
    --dev /dev                                             \
    --proc /proc                                           \
    --ro-bind /usr /usr                                    \
    --ro-bind /etc /etc                                    \
    --ro-bind /sys/fs/cgroup /sys/fs/cgroup                \
    --tmpfs /tmp                                           \
    --hostname "$(cat /etc/hostname):${SCRIPT_NAME}.${ID}" \
    --bind "${SBX_HOME_DIR}" "${HOME}"                     \
    --bind "${PWD}" "${PWD}"                               \
    --chdir "${PWD}"                                       \
)
printf "ok!"

print "setting up root symlinks... "
params+=(                       \
    --symlink /usr/lib /lib     \
    --symlink /usr/lib64 /lib64 \
    --symlink /usr/bin /bin     \
    --symlink /usr/sbin /sbin   \
)
printf "ok!"

print "detecting 'fish'..."
if check_command "fish"; then
    DIR_CONF="${HOME}/.config/fish"
    if [ -d "${DIR_CONF}" ]; then
        params+=(--ro-bind "${DIR_CONF}" "${DIR_CONF}")
        printf "config... "
    else
        printf "no config... "
    fi

    DIR_CACHE="${HOME}/.cache/fish"
    if [ -d "${DIR_CACHE}" ]; then
        params+=(--ro-bind "${DIR_CACHE}" "${DIR_CACHE}")
        printf "cache... "
    else
        printf "no cache... "
    fi

    printf "ok!"
else
    printf " skip!"
fi

print "detecting 'tmux'... "
if check_command "tmux"; then
    DIR_CONF="${HOME}/.config/tmux"
    TMUX_CONF="${DIR_CONF}/tmux.conf"
    if [ -f "${TMUX_CONF}" ]; then
        params+=(--ro-bind "${TMUX_CONF}" "${TMUX_CONF}")
        printf "config... "
    else
        printf "no config... "
    fi

    PLUGINS_DIR="${DIR_CONF}/plugins"
    if [ -d "${PLUGINS_DIR}" ]; then
        printf "plugins... "
        params+=(--ro-bind "${PLUGINS_DIR}" "${PLUGINS_DIR}")
    else
        printf "no plugins... "
    fi

    printf "ok!"
else
    printf "skip!"
fi

print "detecting 'bun'... "
if check_command "bun"; then
    printf "setting up... "
    BUN_PATH=$(which bun)

    if [ -L ${BUN_PATH} ]; then
        printf "resolving link... "
        BUN_PATH=$(realpath "$(dirname ${BUN_PATH})/$(readlink "${BUN_PATH}")")
    fi

    params+=(--ro-bind ${BUN_PATH} ${BUN_PATH})
    printf "ok!"
else
    printf "skip!"
fi

print "detecting rust... "
if check_command "rustup"; then
    ZIG_PATH=$(dirname $(which rustup))
    params+=(--ro-bind "${ZIG_PATH}" "${ZIG_PATH}")
    SBX_ENV_PATH="${SBX_ENV_PATH}:${ZIG_PATH}"

    RUSTUP_HOME=$(rustup show home)
    if [[ -d "${RUSTUP_HOME}" ]]; then
        params+=(--ro-bind "${RUSTUP_HOME}" "${RUSTUP_HOME}")
        printf "toolchain... "
    else
        printf "no toolchain... "
    fi

    printf "ok!"
else
    printf "no rustup, skip!"
fi

print "detecting zig... "
if check_command "zig"; then
    printf "load env... "
    ZIG_ENV=$(zig env) || err_exit "cant load zig env"

    printf "exe... "
    ZIG_EXE=$(echo "${ZIG_ENV}" | grep -oP '\.zig_exe = "\K[^"]+') || err_exit "cant find zig_exe"
    params+=(--ro-bind "${ZIG_EXE}" "${ZIG_EXE}")

    printf "lib... "
    ZIG_LIB=$(echo "${ZIG_ENV}" | grep -oP '\.lib_dir = "\K[^"]+') || err_exit "cant find lib_dir"
    params+=(--ro-bind "${ZIG_LIB}" "${ZIG_LIB}")

    printf "std... "
    ZIG_STD=$(echo "${ZIG_ENV}" | grep -oP '\.std_dir = "\K[^"]+') || err_exit "cant find std_dir"
    params+=(--ro-bind "${ZIG_STD}" "${ZIG_STD}")

    SBX_ENV_PATH="${SBX_ENV_PATH}:$(dirname ${ZIG_EXE})"
    printf "ok!"
else
    printf "skip!"
fi

print "detecting neovim... "
if check_command "nvim"; then
    NVIM_CONFIG="${HOME}/.config/nvim"
    if [[ -d "${NVIM_CONFIG}" ]]; then
        printf "config... "
        params+=(--ro-bind "${NVIM_CONFIG}" "${NVIM_CONFIG}")
    else
        printf "no config... "
    fi

    NVIM_DATA_LAZY="${HOME}/.local/share/nvim/lazy"
    if [[ -d "${NVIM_DATA_LAZY}" ]]; then
        printf "lazy... "
        params+=(--ro-bind "${NVIM_DATA_LAZY}" "${NVIM_DATA_LAZY}")
    else
        printf "no lazy... "
    fi

    NVIM_DATA_MASON="${HOME}/.local/share/nvim/mason"
    if [[ -d "${NVIM_DATA_MASON}" ]]; then
        printf "mason... "
        params+=(--ro-bind "${NVIM_DATA_MASON}" "${NVIM_DATA_MASON}")
    else
        printf "no mason... "
    fi

    printf "ok!"
else
    printf "skip!"
fi

print "detecting custom scripts... "
SCRIPTS_DIR="${HOME}/Scripts"
if [[ -d "${SCRIPTS_DIR}" ]]; then
    params+=(--ro-bind "${SCRIPTS_DIR}" "${SCRIPTS_DIR}")
    SBX_ENV_PATH="${SBX_ENV_PATH}:${SCRIPTS_DIR}"
    printf "ok!"
else
    printf "skip!"
fi

print "setting up env... "
params+=(                           \
    --setenv WSH_ID ${ID}           \
    --setenv USER ${USER}           \
    --setenv HOME ${HOME}           \
    --setenv SHELL ${USE_TERM}      \
    --setenv PATH "${SBX_ENV_PATH}" \
    --setenv LANG "en_US.UTF-8"     \
    --setenv TERM "xterm-256color"  \
    --setenv LC_ALL "en_US.UTF-8"   \
)
printf "ok!"

print "Command: bwrap "
printf '%s ' "${params[@]}"
printf "${USE_TERM} ${@}\n"

bwrap \
    "${params[@]}" \
    ${USE_TERM} \
    "${@}"

print "sandbox exited with ${?}"
