
[window]
opacity = 0.9
padding = { x = 0, y = 0 }
dynamic_padding = true
#decorations = "None"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "SemiBold" }
size = 10

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
#normal = { family = "ComicMono Nerd Font", style = "Bold" }
#size = 11
