import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.8
padding = { x = 0, y = 0 }
dynamic_padding = true
#decorations = "None"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "SemiBold" }
size = 10
#normal = { family = "ComicMono Nerd Font", style = "Bold" }
#size = 11
